/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./../components/AppIcon.vue')['default']
    BaseAvatar: typeof import('./../components/BaseAvatar.vue')['default']
    CodeEditor: typeof import('./../components/CodeEditor.vue')['default']
    EmailCodeInput: typeof import('./../components/EmailCodeInput.vue')['default']
    MarkdownEditor: typeof import('./../components/MarkdownEditor.vue')['default']
    MarkdownView: typeof import('./../components/MarkdownView.vue')['default']
    ModalFooter: typeof import('./../components/ModalFooter.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NProgress: typeof import('naive-ui')['NProgress']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PaginatedDataTable: typeof import('./../components/PaginatedDataTable.vue')['default']
    ProblemMetaBar: typeof import('./../components/problem/ProblemMetaBar.vue')['default']
    ProblemPicker: typeof import('./../components/problemsets/ProblemPicker.vue')['default']
    ProblemSamples: typeof import('./../components/ProblemSamples.vue')['default']
    ProblemStatement: typeof import('./../components/problem/ProblemStatement.vue')['default']
    ProblemWorkbench: typeof import('./../components/problem/ProblemWorkbench.vue')['default']
    RefreshButton: typeof import('./../components/RefreshButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilterBar: typeof import('./../components/SearchFilterBar.vue')['default']
    StatusTag: typeof import('./../components/StatusTag.vue')['default']
    TagPicker: typeof import('./../components/problem/TagPicker.vue')['default']
    TestCaseImporter: typeof import('./../components/problem/TestCaseImporter.vue')['default']
    WizardShell: typeof import('./../components/WizardShell.vue')['default']
    WorkbenchShell: typeof import('./../components/WorkbenchShell.vue')['default']
  }
}
