<script setup lang="ts">
import { ArrowRight, Collection, Trophy, UserFilled } from '@element-plus/icons-vue'
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { useUserStore } from '@/stores/user'
const router=useRouter();const userStore=useUserStore();const {t}=useI18n();const greeting=computed(()=>{if(!userStore.isLoggedIn)return t('home.welcome');const hour=new Date().getHours();const key=hour<6?'dawn':hour<12?'morning':hour<14?'noon':hour<18?'afternoon':'evening';return `${t(`home.${key}`)}，${userStore.user?.nickname??t('home.student')}`});const cards=computed(()=>[{title:t('nav.problems'),desc:t('home.problems'),to:'/problems',icon:Collection,tone:'blue'},{title:t('nav.contests'),desc:t('home.contests'),to:'/contests',icon:Trophy,tone:'amber'},{title:t('nav.teams'),desc:t('home.teams'),to:'/teams',icon:UserFilled,tone:'green'}])
</script>
<template><div class="home"><section class="home__hero"><div><p class="home__kicker">{{t('app.name')}}</p><h1>{{greeting}}</h1><p class="home__intro">{{t('home.intro')}}</p><div v-if="!userStore.isLoggedIn" class="home__hero-actions"><el-button type="primary" size="large" @click="router.push('/register')">{{t('home.createAccount')}}<el-icon><ArrowRight/></el-icon></el-button><el-button size="large" @click="router.push('/login')">{{t('user.login')}}</el-button></div></div><div class="home__hero-art" aria-hidden="true"><span>🐦</span></div></section><section class="home__section"><div class="home__section-head"><div><p class="home__eyebrow">{{t('app.navigation')}}</p><h2>{{t('home.explore')}}</h2></div></div><div class="home__cards"><button v-for="card in cards" :key="card.to" class="home-card" :class="`home-card--${card.tone}`" @click="router.push(card.to)"><span class="home-card__icon"><el-icon><component :is="card.icon"/></el-icon></span><span class="home-card__content"><strong>{{card.title}}</strong><small>{{card.desc}}</small></span><el-icon class="home-card__arrow"><ArrowRight/></el-icon></button></div></section></div></template>
<style scoped>.home{display:grid;gap:28px}.home__hero{min-height:260px;display:flex;align-items:center;justify-content:space-between;gap:24px;padding:36px 42px;border:1px solid color-mix(in srgb,var(--el-color-primary) 16%,var(--app-border));border-radius:var(--app-radius-lg);background:radial-gradient(circle at 88% 15%,#dce6ff 0,transparent 34%),linear-gradient(135deg,#fff 0,#f1f5ff 100%);box-shadow:var(--app-shadow)}.dark .home__hero{background:radial-gradient(circle at 88% 15%,#273f83 0,transparent 34%),linear-gradient(135deg,#171e2d 0,#1b2945 100%)}.home__kicker,.home__eyebrow{margin:0 0 8px;color:var(--el-color-primary);font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.home h1{max-width:720px;margin:0;font-size:clamp(28px,4vw,42px);line-height:1.16;letter-spacing:-.045em}.home__intro{max-width:610px;margin:14px 0 0;color:var(--app-text-muted);font-size:15px;line-height:1.7}.home__hero-actions{display:flex;gap:10px;margin-top:24px}.home__hero-actions :deep(.el-icon){margin-left:4px}.home__hero-art{width:142px;height:142px;display:grid;place-items:center;flex:0 0 auto;border-radius:42px;background:linear-gradient(145deg,var(--el-color-primary),#738ffa);box-shadow:0 18px 34px rgba(56,103,244,.25);transform:rotate(8deg)}.home__hero-art span{font-size:72px;transform:rotate(-8deg)}.home__section-head{display:flex;justify-content:space-between;align-items:end}.home__section-head h2{margin:0;font-size:20px;letter-spacing:-.025em}.home__cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px;margin-top:14px}.home-card{display:flex;align-items:center;gap:14px;width:100%;padding:18px;text-align:left;border:1px solid var(--app-border);border-radius:var(--app-radius);background:var(--app-surface);cursor:pointer;transition:transform .2s,box-shadow .2s,border-color .2s}.home-card:hover{transform:translateY(-3px);border-color:color-mix(in srgb,var(--el-color-primary) 32%,var(--app-border));box-shadow:var(--app-shadow-hover)}.home-card__icon{width:42px;height:42px;display:grid;place-items:center;flex:0 0 auto;border-radius:13px;font-size:20px}.home-card--blue .home-card__icon{color:#3867f4;background:#edf2ff}.home-card--amber .home-card__icon{color:#d98a00;background:#fff5df}.home-card--green .home-card__icon{color:#26945a;background:#e6f8ed}.home-card--violet .home-card__icon{color:#7d55da;background:#f0eaff}.home-card__content{display:grid;gap:4px;min-width:0}.home-card__content strong{font-size:15px}.home-card__content small{color:var(--app-text-muted);font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.home-card__arrow{margin-left:auto;color:var(--app-text-muted)}@media(max-width:680px){.home__hero{min-height:unset;padding:28px;align-items:flex-start}.home__hero-art{display:none}.home__hero-actions{flex-wrap:wrap}.home__hero-actions .el-button{flex:1}.home__cards{grid-template-columns:1fr}}</style>
