<script setup lang="ts">
import { ElMessage } from 'element-plus'
import { reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { useUserStore } from '@/stores/user'
const router=useRouter();const route=useRoute();const userStore=useUserStore();const {t}=useI18n();const form=reactive({email:'',password:''});const loading=ref(false)
async function onSubmit(){if(!form.email||!form.password)return ElMessage.warning(t('auth.enterEmailPassword'));loading.value=true;try{await userStore.login(form.email,form.password);ElMessage.success(t('auth.loginSuccess'));router.push(typeof route.query.redirect==='string'&&route.query.redirect?route.query.redirect:'/')}catch(e){ElMessage.error(e instanceof Error?e.message:t('auth.loginFailed'))}finally{loading.value=false}}
</script>
<template><div class="auth-page"><section class="auth-visual"><div class="auth-visual__brand"><span>🐦</span><strong>PigeonOJ</strong></div><div><p class="auth-visual__eyebrow">{{t('app.tagline')}}</p><h1>{{t('auth.loginTitle')}}</h1><p>{{t('home.intro')}}</p></div><div class="auth-visual__orb" aria-hidden="true">&lt;/&gt;</div></section><main class="auth-panel"><div class="auth-card"><div class="auth-card__heading"><p>{{t('app.name')}}</p><h2>{{t('auth.loginTitle')}}</h2></div><el-form label-position="top" class="auth-card__form" @submit.prevent="onSubmit"><el-form-item :label="t('auth.email')"><el-input v-model="form.email" placeholder="you@example.com" autocomplete="username" size="large"/></el-form-item><el-form-item :label="t('auth.password')"><el-input v-model="form.password" type="password" show-password :placeholder="t('auth.passwordPlaceholder')" autocomplete="current-password" size="large" @keyup.enter="onSubmit"/></el-form-item><el-button type="primary" size="large" class="auth-card__submit" :loading="loading" @click="onSubmit">{{t('user.login')}}</el-button></el-form><p class="auth-card__footer">{{t('auth.noAccount')}} <el-link type="primary" @click="router.push('/register')">{{t('auth.registerNow')}}</el-link></p></div></main></div></template>
<style scoped>.auth-page{display:grid;grid-template-columns:minmax(360px,1.05fr) minmax(420px,.95fr);min-height:100dvh;background:var(--app-surface)}.auth-visual{position:relative;display:flex;flex-direction:column;justify-content:space-between;padding:44px clamp(36px,7vw,100px);overflow:hidden;color:#fff;background:linear-gradient(145deg,#19316c 0%,#3867f4 56%,#6c8afb 100%)}.auth-visual__brand{display:flex;align-items:center;gap:10px;font-size:19px}.auth-visual__brand span{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;background:rgba(255,255,255,.15);font-size:20px}.auth-visual h1{max-width:510px;margin:10px 0 14px;font-size:clamp(34px,4vw,54px);line-height:1.1;letter-spacing:-.05em}.auth-visual p{max-width:480px;margin:0;color:rgba(255,255,255,.76);font-size:15px;line-height:1.75}.auth-visual__eyebrow{color:#cfdbff!important;font-size:11px!important;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.auth-visual__orb{position:absolute;right:-70px;bottom:-60px;display:grid;place-items:center;width:280px;height:280px;border:1px solid rgba(255,255,255,.23);border-radius:50%;color:rgba(255,255,255,.18);font-size:90px;font-weight:800;transform:rotate(-16deg)}.auth-panel{display:grid;place-items:center;padding:32px;background:var(--app-canvas)}.auth-card{width:min(100%,420px);padding:38px;border:1px solid var(--app-border);border-radius:var(--app-radius-lg);background:var(--app-surface);box-shadow:var(--app-shadow)}.auth-card__heading p{margin:0 0 8px;color:var(--el-color-primary);font-size:12px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.auth-card__heading h2{margin:0 0 28px;font-size:28px;letter-spacing:-.035em}.auth-card__form :deep(.el-form-item){margin-bottom:20px}.auth-card__form :deep(.el-form-item__label){font-weight:680}.auth-card__submit{width:100%;margin-top:6px}.auth-card__footer{margin:22px 0 0;text-align:center;color:var(--app-text-muted);font-size:13px}@media(max-width:800px){.auth-page{display:block}.auth-visual{min-height:220px;padding:28px}.auth-visual h1{font-size:32px}.auth-visual__orb{width:170px;height:170px;font-size:55px}.auth-panel{min-height:calc(100dvh - 220px);padding:24px 16px}.auth-card{padding:28px 24px}}</style>
