<script setup lang="ts">
import { ElMessage } from 'element-plus'
import { onBeforeUnmount, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import * as authApi from '@/api/auth'
const router=useRouter(); const { t }=useI18n(); const form=reactive({email:'',nickname:'',code:'',password:'',confirm:''}); const loading=ref(false); const sending=ref(false); const countdown=ref(0); let timer:ReturnType<typeof setInterval>|null=null
function startCountdown(){countdown.value=60;timer=setInterval(()=>{if(--countdown.value<=0&&timer){clearInterval(timer);timer=null}},1000)} onBeforeUnmount(()=>{if(timer)clearInterval(timer)})
async function onSendCode(){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))return ElMessage.warning(t('auth.validEmail'));sending.value=true;try{const res=await authApi.sendEmailCode(form.email,'register');if(res?.hint)ElMessage.info(res.hint);else ElMessage.success(t('auth.codeSent'));startCountdown()}catch(e){ElMessage.error(e instanceof Error?e.message:t('auth.sendFailed'))}finally{sending.value=false}}
async function onSubmit(){if(!form.email||!form.nickname||!form.code||!form.password)return ElMessage.warning(t('auth.completeRegistration'));if(form.password.length<6)return ElMessage.warning(t('auth.passwordTooShort'));if(form.password!==form.confirm)return ElMessage.warning(t('auth.passwordMismatch'));loading.value=true;try{await authApi.register({email:form.email,code:form.code,password:form.password,nickname:form.nickname});ElMessage.success(t('auth.registerSuccess'));router.push('/login')}catch(e){ElMessage.error(e instanceof Error?e.message:t('auth.registerFailed'))}finally{loading.value=false}}
</script>
<template><div class="register-page"><header class="register-page__brand" @click="router.push('/')"><span>🐦</span><strong>PigeonOJ</strong></header><main class="register-card"><div class="register-card__heading"><p>{{t('app.tagline')}}</p><h1>{{t('auth.registerTitle')}}</h1><span>{{t('home.intro')}}</span></div><el-form label-position="top" class="register-card__form" @submit.prevent="onSubmit"><el-form-item :label="t('auth.email')"><el-input v-model="form.email" placeholder="you@example.com" autocomplete="email" size="large"/></el-form-item><el-form-item :label="t('auth.nickname')"><el-input v-model="form.nickname" :placeholder="t('auth.nicknamePlaceholder')" maxlength="64" size="large"/></el-form-item><el-form-item :label="t('auth.code')"><div class="register-card__code-row"><el-input v-model="form.code" :placeholder="t('auth.code')" maxlength="6" size="large" @keyup.enter="onSubmit"/><el-button :disabled="countdown>0" :loading="sending" size="large" @click="onSendCode">{{countdown>0?t('auth.resend',{seconds:countdown}):t('auth.getCode')}}</el-button></div></el-form-item><el-form-item :label="t('auth.password')"><el-input v-model="form.password" type="password" show-password :placeholder="t('auth.passwordMin')" autocomplete="new-password" size="large"/></el-form-item><el-form-item :label="t('auth.confirmPassword')"><el-input v-model="form.confirm" type="password" show-password :placeholder="t('auth.repeatPassword')" size="large" @keyup.enter="onSubmit"/></el-form-item><el-button type="primary" size="large" class="register-card__submit" :loading="loading" @click="onSubmit">{{t('user.register')}}</el-button></el-form><p class="register-card__footer">{{t('auth.hasAccount')}} <el-link type="primary" @click="router.push('/login')">{{t('auth.backLogin')}}</el-link></p></main></div></template>
<style scoped>.register-page{min-height:100dvh;padding:28px;background:radial-gradient(circle at 8% 5%,#e1e9ff 0,transparent 25%),var(--app-canvas)}.register-page__brand{display:flex;align-items:center;gap:9px;width:max-content;cursor:pointer;font-size:18px}.register-page__brand span{display:grid;place-items:center;width:36px;height:36px;border-radius:11px;background:var(--el-color-primary-light-8)}.register-card{width:min(100%,500px);margin:clamp(24px,8vh,84px) auto 40px;padding:36px 40px;border:1px solid var(--app-border);border-radius:var(--app-radius-lg);background:var(--app-surface);box-shadow:var(--app-shadow)}.register-card__heading p{margin:0 0 8px;color:var(--el-color-primary);font-size:11px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.register-card__heading h1{margin:0;font-size:30px;letter-spacing:-.04em}.register-card__heading span{display:block;margin:10px 0 26px;color:var(--app-text-muted);font-size:13px;line-height:1.65}.register-card__form :deep(.el-form-item){margin-bottom:18px}.register-card__form :deep(.el-form-item__label){font-weight:680}.register-card__code-row{display:flex;gap:10px}.register-card__code-row .el-input{flex:1}.register-card__submit{width:100%;margin-top:4px}.register-card__footer{margin:22px 0 0;text-align:center;color:var(--app-text-muted);font-size:13px}@media(max-width:560px){.register-page{padding:20px 16px}.register-card{margin:28px auto;padding:28px 22px}.register-card__code-row{gap:8px}.register-card__code-row :deep(.el-button){padding:0 10px}}</style>
