<script setup lang="ts">
import { ElMessage, ElMessageBox } from 'element-plus'
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import * as authApi from '@/api/auth'
import { useUserStore } from '@/stores/user'
const router=useRouter();const {t}=useI18n();const userStore=useUserStore();const pwdForm=reactive({old_password:'',new_password:'',confirm:''});const pwdLoading=ref(false);const emailForm=reactive({new_email:'',code:''});const emailLoading=ref(false);const sending=ref(false);const countdown=ref(0);let timer:ReturnType<typeof setInterval>|null=null
async function onChangePassword(){if(!pwdForm.old_password||!pwdForm.new_password)return ElMessage.warning(t('security.fillPasswords'));if(pwdForm.new_password.length<6)return ElMessage.warning(t('security.newPasswordShort'));if(pwdForm.new_password!==pwdForm.confirm)return ElMessage.warning(t('security.newPasswordMismatch'));pwdLoading.value=true;try{await authApi.changePassword(pwdForm.old_password,pwdForm.new_password);ElMessage.success(t('security.passwordChanged'));Object.assign(pwdForm,{old_password:'',new_password:'',confirm:''})}catch(e){ElMessage.error(e instanceof Error?e.message:t('security.passwordChangeFailed'))}finally{pwdLoading.value=false}}function startCountdown(){countdown.value=60;timer=setInterval(()=>{if(--countdown.value<=0&&timer){clearInterval(timer);timer=null}},1000)}async function onSendEmailCode(){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(emailForm.new_email))return ElMessage.warning(t('auth.validEmail'));sending.value=true;try{const res=await authApi.sendEmailCode(emailForm.new_email,'change_email');if(res?.hint)ElMessage.info(res.hint);else ElMessage.success(t('auth.codeSent'));startCountdown()}catch(e){ElMessage.error(e instanceof Error?e.message:t('security.sendCodeFailed'))}finally{sending.value=false}}async function onChangeEmail(){if(!emailForm.new_email||!emailForm.code)return ElMessage.warning(t('security.enterEmailCode'));emailLoading.value=true;try{await authApi.changeEmail(emailForm.new_email,emailForm.code);ElMessage.success(t('security.emailChanged'));Object.assign(emailForm,{new_email:'',code:''})}catch(e){ElMessage.error(e instanceof Error?e.message:t('security.emailChangeFailed'))}finally{emailLoading.value=false}}async function onDeactivate(){try{const{value}=await ElMessageBox.prompt(t('security.deactivatePrompt'),t('security.deactivateTitle'),{confirmButtonText:t('security.deactivateConfirm'),cancelButtonText:t('action.cancel'),inputType:'password',inputPlaceholder:t('auth.password'),type:'warning'});await userStore.deactivate(value);ElMessage.success(t('security.deactivated'));router.push('/login')}catch(e){if(e==='cancel'||e==='close')return;ElMessage.error(e instanceof Error?e.message:t('common.operationFailed'))}}
</script>
<template><div class="security-page"><header class="page-heading"><div><p class="page-heading__eyebrow">{{t('nav.userSettings')}}</p><h1>{{t('user.security')}}</h1><p>{{t('security.descriptionText')}}</p></div></header><div class="security-grid"><el-card shadow="never"><template #header>{{t('security.changePassword')}}</template><el-form label-position="top"><el-form-item :label="t('security.oldPassword')"><el-input v-model="pwdForm.old_password" type="password" show-password autocomplete="current-password" size="large"/></el-form-item><el-form-item :label="t('security.newPassword')"><el-input v-model="pwdForm.new_password" type="password" show-password autocomplete="new-password" size="large"/></el-form-item><el-form-item :label="t('security.confirmNewPassword')"><el-input v-model="pwdForm.confirm" type="password" show-password size="large" @keyup.enter="onChangePassword"/></el-form-item><el-button type="primary" :loading="pwdLoading" @click="onChangePassword">{{t('security.changePassword')}}</el-button></el-form></el-card><el-card shadow="never"><template #header>{{t('security.changeEmail')}}</template><el-form label-position="top"><el-form-item :label="t('security.newEmail')"><el-input v-model="emailForm.new_email" placeholder="you@example.com" size="large"/></el-form-item><el-form-item :label="t('auth.code')"><div class="code-row"><el-input v-model="emailForm.code" :placeholder="t('auth.code')" maxlength="6" size="large" @keyup.enter="onChangeEmail"/><el-button :disabled="countdown>0" :loading="sending" size="large" @click="onSendEmailCode">{{countdown>0?t('auth.resend',{seconds:countdown}):t('auth.getCode')}}</el-button></div></el-form-item><el-button type="primary" :loading="emailLoading" @click="onChangeEmail">{{t('security.confirmEmailChange')}}</el-button></el-form></el-card></div><el-card shadow="never" class="danger-card"><template #header>{{t('security.danger')}}</template><div class="danger-card__content"><div><strong>{{t('security.deactivate')}}</strong><p>{{t('security.deactivateDescription')}}</p></div><el-button type="danger" plain @click="onDeactivate">{{t('security.deactivate')}}</el-button></div></el-card></div></template>
<style scoped>.security-page{display:grid;gap:20px;max-width:1040px}.page-heading__eyebrow{margin:0 0 6px;color:var(--el-color-primary);font-size:11px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.page-heading h1{margin:0;font-size:26px;letter-spacing:-.035em}.page-heading p:not(.page-heading__eyebrow){margin:8px 0 0;color:var(--app-text-muted);font-size:13px}.security-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.security-grid :deep(.el-form-item){margin-bottom:20px}.security-grid :deep(.el-form-item__label){font-weight:680}.code-row{display:flex;gap:10px}.code-row .el-input{flex:1}.danger-card{border-color:color-mix(in srgb,var(--el-color-danger) 26%,var(--app-border))}.danger-card__content{display:flex;align-items:center;justify-content:space-between;gap:18px}.danger-card__content strong{font-size:15px}.danger-card__content p{margin:6px 0 0;color:var(--app-text-muted);font-size:12px;line-height:1.55}@media(max-width:720px){.security-grid{grid-template-columns:1fr}.danger-card__content{align-items:start;flex-direction:column}.danger-card__content .el-button{width:100%}}</style>
