<script setup lang="ts">
import { ElMessage } from 'element-plus'
import { computed, onMounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import * as adminApi from '@/api/admin'
import type { Report, ReportStatus, ReportType } from '@/types'
import { REPORT_STATUS, REPORT_TYPE } from '@/constants/dict'
import { formatDateTime } from '@/utils/format'
const {t}=useI18n();const loading=ref(false);const list=ref<Report[]>([]);const total=ref(0);const query=reactive({page:1,page_size:20,status:'' as ReportStatus|''});const handleDialog=ref(false);const handleTarget=ref<Report|null>(null);const handleAction=ref<'handled'|'ignored'>('handled');const handling=ref(false)
async function load(){loading.value=true;try{const res=await adminApi.adminListReports(query);list.value=res.items;total.value=res.total}catch(e){ElMessage.error(e instanceof Error?e.message:t('common.loadFailed'))}finally{loading.value=false}}onMounted(load);function onFilter(){query.page=1;load()}function openHandle(report:Report){handleTarget.value=report;handleAction.value='handled';handleDialog.value=true}async function submitHandle(){if(!handleTarget.value)return;handling.value=true;try{await adminApi.adminHandleReport(handleTarget.value.id,handleAction.value);ElMessage.success(handleAction.value==='handled'?t('admin.reports.handleSuccess'):t('admin.reports.ignored'));handleDialog.value=false;await load()}catch(e){ElMessage.error(e instanceof Error?e.message:t('common.operationFailed'))}finally{handling.value=false}}const statusOptions=computed(()=>Object.entries(REPORT_STATUS).map(([v,m])=>({value:v,label:m.label})));function targetText(row:Report){return row.target_summary??`#${row.target_id.slice(0,8)}`}
</script>
<template><el-card shadow="never"><template #header><div class="reports__header"><span>{{t('admin.reports.title')}}</span><el-select v-model="query.status" :placeholder="t('common.allStatus')" clearable class="reports__filter" @change="onFilter"><el-option v-for="s in statusOptions" :key="s.value" :label="s.label" :value="s.value"/></el-select></div></template><el-table v-loading="loading" :data="list" stripe><el-table-column :label="t('admin.reports.type')" width="90"><template #default="{row}"><el-tag size="small" :type="row.target_type==='comment'?'info':row.target_type==='post'?'warning':'primary'">{{REPORT_TYPE[row.target_type as ReportType]??row.target_type}}</el-tag></template></el-table-column><el-table-column :label="t('admin.reports.target')" min-width="220"><template #default="{row}"><div>{{targetText(row)}}</div><div class="reports__target-id">{{row.target_id}}</div></template></el-table-column><el-table-column prop="reporter_nickname" :label="t('admin.reports.reporter')" width="120"/><el-table-column prop="reason" :label="t('admin.reports.reason')" min-width="180" show-overflow-tooltip/><el-table-column :label="t('admin.reports.status')" width="100"><template #default="{row}"><el-tag size="small" :type="REPORT_STATUS[row.status as ReportStatus]?.tag??'info'">{{REPORT_STATUS[row.status as ReportStatus]?.label??row.status}}</el-tag></template></el-table-column><el-table-column :label="t('admin.reports.createdAt')" width="150"><template #default="{row}">{{formatDateTime(row.created_at)}}</template></el-table-column><el-table-column :label="t('admin.reports.handledAt')" width="150"><template #default="{row}">{{formatDateTime(row.handled_at)}}</template></el-table-column><el-table-column :label="t('action.edit')" width="100" fixed="right"><template #default="{row}"><el-button v-if="row.status==='pending'" link type="primary" @click="openHandle(row)">{{t('action.handle')}}</el-button><span v-else class="reports__muted">{{t('admin.reports.handled')}}</span></template></el-table-column><template #empty><el-empty :description="t('admin.reports.empty')" :image-size="80"/></template></el-table><div class="reports__pager"><el-pagination v-model:current-page="query.page" v-model:page-size="query.page_size" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" background @change="load"/></div><el-dialog v-model="handleDialog" :title="t('admin.reports.handleTitle',{target:handleTarget?targetText(handleTarget):''})" width="440px"><el-radio-group v-model="handleAction" class="reports__actions"><el-radio value="handled">{{t('admin.reports.approve')}}</el-radio><el-radio value="ignored">{{t('admin.reports.ignore')}}</el-radio></el-radio-group><template #footer><el-button @click="handleDialog=false">{{t('action.cancel')}}</el-button><el-button type="primary" :loading="handling" @click="submitHandle">{{t('action.confirm')}}</el-button></template></el-dialog></el-card></template>
<style scoped>.reports__header{display:flex;align-items:center;justify-content:space-between}.reports__filter{width:140px}.reports__target-id,.reports__muted{font-size:12px;color:var(--el-text-color-secondary)}.reports__pager{display:flex;justify-content:flex-end;margin-top:14px}.reports__actions{display:flex;flex-direction:column;gap:8px}</style>
