<script setup lang="ts">
import { ElMessage } from 'element-plus'
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import * as adminApi from '@/api/admin'
import type { SandboxNode } from '@/types'
import { SANDBOX_STATUS } from '@/constants/dict'
import { formatDateTime } from '@/utils/format'
const {t}=useI18n();const loading=ref(false);const nodes=ref<SandboxNode[]>([])
async function load(){loading.value=true;try{nodes.value=await adminApi.adminSandboxStatus()}catch(e){ElMessage.error(e instanceof Error?e.message:t('common.loadFailed'))}finally{loading.value=false}}onMounted(load)
const onlineCount=computed(()=>nodes.value.filter(n=>n.status==='online').length);const totalLoad=computed(()=>{const online=nodes.value.filter(n=>n.status==='online');return online.length?online.reduce((s,n)=>s+n.load,0)/online.length:0})
</script>
<template><el-card shadow="never"><template #header><div class="sandbox__header"><span>{{t('admin.sandbox.title')}}</span><el-button size="small" :loading="loading" @click="load">{{t('action.refresh')}}</el-button></div></template><div class="sandbox__summary"><el-tag type="success">{{t('admin.sandbox.online',{online:onlineCount,total:nodes.length})}}</el-tag><el-tag type="info">{{t('admin.sandbox.avgLoad',{load:(totalLoad*100).toFixed(0)})}}</el-tag></div><el-table v-loading="loading" :data="nodes" stripe><el-table-column prop="name" :label="t('admin.sandbox.node')" min-width="150"><template #default="{row}"><code>{{row.name}}</code></template></el-table-column><el-table-column :label="t('admin.sandbox.status')" width="90"><template #default="{row}"><el-tag size="small" :type="SANDBOX_STATUS[row.status as SandboxNode['status']]?.tag??'info'">{{SANDBOX_STATUS[row.status as SandboxNode['status']]?.label??row.status}}</el-tag></template></el-table-column><el-table-column :label="t('admin.sandbox.load')" min-width="160"><template #default="{row}"><el-progress :percentage="Math.round(row.load*100)" :status="row.load>.8?'exception':row.load>.5?'warning':undefined"/></template></el-table-column><el-table-column label="CPU" width="120"><template #default="{row}">{{row.cpu_usage}}%</template></el-table-column><el-table-column :label="t('admin.sandbox.memory')" width="120"><template #default="{row}">{{row.memory_usage}}%</template></el-table-column><el-table-column prop="running_tasks" :label="t('admin.sandbox.tasks')" width="100" align="right"/><el-table-column prop="version" :label="t('admin.sandbox.version')" min-width="220" show-overflow-tooltip/><el-table-column :label="t('admin.sandbox.heartbeat')" width="150"><template #default="{row}">{{formatDateTime(row.last_heartbeat_at)}}</template></el-table-column><template #empty><el-empty :description="t('admin.sandbox.empty')" :image-size="80"/></template></el-table><p class="sandbox__tip">{{t('admin.sandbox.tip')}}</p></el-card></template>
<style scoped>.sandbox__header{display:flex;align-items:center;justify-content:space-between}.sandbox__summary{display:flex;gap:8px;margin-bottom:14px}.sandbox__tip{margin:12px 0 0;font-size:12px;color:var(--el-text-color-secondary)}</style>
