<script setup lang="ts">
import { Expand, Fold, House } from '@element-plus/icons-vue'
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { useAppStore } from '@/stores/app'
import LanguageSwitcher from './components/LanguageSwitcher.vue'
import SectionTabs from './components/SectionTabs.vue'
import SideMenu from './components/SideMenu.vue'
import UserCard from './components/UserCard.vue'
const route=useRoute();const router=useRouter();const appStore=useAppStore();const {t}=useI18n();const pageTitle=computed(()=>route.meta.titleKey?t(String(route.meta.titleKey)):route.meta.title??'');const sectionTitle=computed(()=>route.matched[1]?.meta?.titleKey?t(String(route.matched[1].meta.titleKey)):route.matched[1]?.meta?.title??'')
</script>
<template><el-container class="app-layout"><el-aside :width="appStore.sidebarCollapsed?'76px':'264px'" class="app-aside"><div class="app-logo" role="button" tabindex="0" @click="router.push('/')" @keyup.enter="router.push('/')"><span class="app-logo__mark">🐦</span><span v-show="!appStore.sidebarCollapsed" class="app-logo__brand"><strong>PigeonOJ</strong><small>{{t('app.tagline')}}</small></span></div><SideMenu/><UserCard/></el-aside><el-container class="app-body"><el-header class="app-header" height="68px"><div class="app-header__context"><el-tooltip :content="appStore.sidebarCollapsed?t('sidebar.expand'):t('sidebar.collapse')"><el-button text circle class="app-header__toggle" :aria-label="appStore.sidebarCollapsed?t('sidebar.expand'):t('sidebar.collapse')" @click="appStore.toggleSidebar()"><el-icon :size="18"><Fold v-if="!appStore.sidebarCollapsed"/><Expand v-else/></el-icon></el-button></el-tooltip><div class="app-header__titles"><div v-if="sectionTitle&&sectionTitle!==pageTitle" class="app-header__eyebrow"><el-icon><House/></el-icon>{{sectionTitle}}</div><span class="app-header__title">{{pageTitle}}</span></div></div><div class="app-header__actions"><LanguageSwitcher/></div></el-header><SectionTabs/><el-main class="app-main"><div class="app-main__content"><router-view/></div></el-main></el-container></el-container></template>
<style scoped>
.app-layout{height:100dvh;background:var(--app-canvas)}.app-aside{display:flex;flex-direction:column;padding:12px 10px 10px;border-right:1px solid var(--app-border);background:var(--app-surface);transition:width .24s ease;overflow:hidden}.app-logo{height:58px;display:flex;align-items:center;gap:11px;padding:0 10px;cursor:pointer;flex-shrink:0;border-radius:12px;outline:none}.app-logo:focus-visible{box-shadow:0 0 0 3px var(--el-color-primary-light-7)}.app-logo__mark{width:38px;height:38px;display:grid;place-items:center;border-radius:12px;font-size:21px;background:linear-gradient(145deg,var(--el-color-primary-light-8),var(--el-color-primary-light-9))}.app-logo__brand{display:grid;line-height:1.15;white-space:nowrap}.app-logo__brand strong{font-size:17px;letter-spacing:-.02em}.app-logo__brand small{margin-top:3px;color:var(--app-text-muted);font-size:10px;font-weight:650;letter-spacing:.06em;text-transform:uppercase}.app-aside :deep(.side-menu-scroll){margin-top:16px}.app-header{height:68px;display:flex;align-items:center;justify-content:space-between;padding:0 28px;border-bottom:1px solid var(--app-border);background:color-mix(in srgb,var(--app-surface) 92%,transparent);backdrop-filter:blur(16px)}.app-header__context,.app-header__actions{display:flex;align-items:center;gap:12px}.app-header__toggle{color:var(--app-text-muted)}.app-header__titles{display:grid;gap:2px}.app-header__eyebrow{display:flex;align-items:center;gap:5px;color:var(--app-text-muted);font-size:11px;font-weight:700;letter-spacing:.03em}.app-header__title{font-size:18px;font-weight:720;letter-spacing:-.02em}.app-main{padding:28px;overflow:auto;background:var(--app-canvas)}.app-main__content{max-width:1440px;margin:0 auto}@media(max-width:767px){.app-aside{position:fixed;z-index:30;height:100dvh;box-shadow:var(--app-shadow)}.app-body{margin-left:76px}.app-header{padding:0 16px}.app-main{padding:16px}.app-header__eyebrow{display:none}.app-header__title{font-size:16px}}
</style>
